remote 10.156.17.17 1194
client
proto udp4
dev tap
resolv-retry infinite
nobind
tls-cipher "DEFAULT:@SECLEVEL=0"
data-ciphers none
persist-key
ca /vpn/vmiigsi001.b0197_ca.crt
cert /vpn/vmiigsi001.b0197_pay.crt
key /vpn/vmiigsi001.b0197_pay.key
verb 3
comp-lzo
